version = "1.0.0"
owner = "etienne@scalingo.com"
team = "IST"
description = "Buildpack for Node.js and Meteor apps."
languages = ["shell"]
destination_server = []
flags = ["buildpack"]
dependencies = []
